USE [master]
GO

/****** Object:  Database [EPasport]    Script Date: 08.03.2025 17:59:24 ******/
CREATE DATABASE [EPasport]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EPasport', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\EPasport.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EPasport_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\EPasport_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EPasport].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EPasport] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EPasport] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EPasport] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EPasport] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EPasport] SET ARITHABORT OFF 
GO

ALTER DATABASE [EPasport] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EPasport] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EPasport] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EPasport] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EPasport] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EPasport] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EPasport] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EPasport] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EPasport] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EPasport] SET  ENABLE_BROKER 
GO

ALTER DATABASE [EPasport] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EPasport] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EPasport] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EPasport] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EPasport] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EPasport] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EPasport] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EPasport] SET RECOVERY FULL 
GO

ALTER DATABASE [EPasport] SET  MULTI_USER 
GO

ALTER DATABASE [EPasport] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EPasport] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EPasport] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EPasport] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [EPasport] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EPasport] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [EPasport] SET QUERY_STORE = OFF
GO

ALTER DATABASE [EPasport] SET  READ_WRITE 
GO

